### PR TITLE
Save text when you submit text with keyboard

### PR DESCRIPTION
**Pull request by emiksk**
Related #40 

@rkonno 
plz review this!

### CODE REVIEW

**Comment by rkonno** [comment]
@emiksk 
That’s a cool improvement.
I confirmed the expected operation!

There seems to be a conflict with the change of the previous PR.
Can you solve it? :)

**Comment by emiksk** [comment]
@rkonno 
I fixed it!
The `click.maimodorun` for bindCancel doesn't work I expected, so I used `mousedown.maimodorun`.

**Comment by rkonno** [comment]
@emiksk 
Thanks!

> The `click.maimodorun` for bindCancel doesn't work I expected, so I used `mousedown.maimodorun`.

Umm...Certainly, the ignition timing of each event is a mystery...

**Comment by emiksk** [comment]
Thank!

**Pull request merged**
