### PR TITLE
Support message page to save and recovery text

### PR DESCRIPTION
**Pull request by emiksk**
Related #27 
Support message page!

### CODE REVIEW

**Comment by emiksk** [comment]
@rkonno 
Please fix popuo.html because text type of messages (e.g. メッセージ / 本文) is shown across two lines in popup.

**Comment by rkonno** [comment]
@emiksk 
Good PR! 👍 
Fixed style collapse due to the number of tag characters!

### diff
|Before|After|
|---|---|
|||

Please confirm! 🙂

**Comment by emiksk** [comment]
@rkonno 
Thanks!
We should reconsider the design of popup later, you know.

**Comment by emiksk** [comment]
Merge!

**Comment by emiksk** [comment]
Close #29

**Pull request merged**
